const CREATE_JOB_ACTION_TYPE = {
  API_CREATEJOB: 'API_CREATEJOB',
  API_CREATEJOB_SUCCESS: 'API_CREATEJOB_SUCCESS',
  API_CREATEJOB_ERROR: 'API_CREATEJOB_ERROR',
};
export default CREATE_JOB_ACTION_TYPE;
