import { StyleSheet } from "react-native";
import { _COLORS, FONTFAMILY } from "../../../Themes";

import { fontFamily } from "../../../Themes/FontStyle/FontStyle";
export const PropertyListCSS = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: _COLORS.Kodie_WhiteColor,
  },
  line: {
    borderBottomWidth: 1,
    borderBottomColor: _COLORS.Kodie_GrayColor,
  },
  item_style: {
    fontSize: 12,
    fontFamily: fontFamily.K_Regular,
    color: _COLORS.Kodie_VeryLightGrayColor,
  },
  flat_MainView: { flex: 1, flexDirection: "row", alignItems: "center" },
  AllView: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 15,
    paddingVertical: 2,
    paddingHorizontal: 8,
    backgroundColor: _COLORS.Kodie_BlackColor,
    marginTop: 15,
  },
  flatlistView: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: _COLORS.Kodie_GrayColor,
    paddingHorizontal: 10,
    paddingVertical: 2,
    marginTop: 15,
    marginHorizontal: 5,
    borderRadius: 15,
  },
  round: {
    height: 8,
    width: 8,
    borderRadius: 8 / 2,
    borderWidth: 1,
    borderColor: _COLORS.Kodie_LightGrayColor,
    backgroundColor: _COLORS.Kodie_GrayColor,
    alignSelf: "center",
    marginRight: 5,
  },
  Container: {
    marginHorizontal: 16,
  },
  flexContainer: { flex: 1 },
  apartmentText: { fontSize: 12, color: _COLORS.Kodie_BlackColor },
  locationText: {
    flex: 1,
    fontSize: 10,
    color: _COLORS.Kodie_MediumGrayColor,
  },
  imageStyle: {
    flex: 0.5,
    height: 65,
    width: 65,
    borderRadius: 10,
    alignSelf: "center",
  },
  buttonView: {
    flex: 0.7,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: _COLORS.Kodie_LightOrange,
    backgroundColor: _COLORS.Kodie_LightOrange,
    borderRadius: 15,
    paddingHorizontal: 1,
    paddingVertical: 1,
    marginLeft: 10,
  },
  roundButton: {
    height: 6,
    width: 6,
    borderRadius: 6 / 2,
    alignSelf: "center",
    marginRight: 5,
  },
  buttonText: {
    fontSize: 12,
    color: _COLORS.Kodie_DarkOrange,
    fontFamily: fontFamily.K_Bold,
    alignSelf: "center",
  },
  flatListContainer: { marginHorizontal: 30 },
  expandedContent: {
    marginHorizontal: 30,
    flex: 1,
    flexDirection: "row",
    alignSelf: "center",
  },
  noteStyle: {
    flexDirection: "row",
    alignSelf: "flex-end",
    marginBottom: 15,
  },
  noteIcon: { height: 25, width: 25, marginRight: 8 },
  rentView: { flex: 1, alignItems: "flex-end" },
  bottomModal_container: {
    borderWidth: 0.5,
    borderColor: _COLORS.Kodie_LightGrayColor,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    elevation: 10,
  },
});
