const ADD_PROPERTY_SECONDSTEP_ACTION_TYPES = {
  // for Subscription
  API_ADDPROPERTYSECONDSTEP: 'API_ADDPROPERTYSECONDSTEP',
  API_ADDPROPERTYSECONDSTEP_SUCCESS: 'API_ADDPROPERTYSECONDSTEP_SUCCESS',
  API_ADDPROPERTYSECONDSTEP_ERROR:
    'API_ADDPROPERTYSECONDSTEP_ERROR',
    CLEAR_PROPERTY_ID : 'CLEAR_PROPERTY_Id'
};
export default ADD_PROPERTY_SECONDSTEP_ACTION_TYPES;
