import { StyleSheet } from "react-native";
import { _COLORS, FONTFAMILY } from "../../../../Themes";

export const RantalOfferCss = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: _COLORS.Kodie_WhiteColor,
  },
  Container: { marginHorizontal: 16 },
  flat_MainView: { flex: 1, flexDirection: "row", alignItems: "center" },
  flexContainer: { flex: 1 },
  apartmentText: { fontSize: 12, color: _COLORS.Kodie_BlackColor },
  locationText: {
    flex: 1,
    fontSize: 10,
    color: _COLORS.Kodie_MediumGrayColor,
  },
  imageStyle: {
    flex: 0.5,
    height: 65,
    width: 65,
    borderRadius: 10,
    alignSelf: "center",
  },
  buttonView: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: _COLORS.Kodie_LightOrange,
    backgroundColor: _COLORS.Kodie_LightOrange,
    borderRadius: 15,
    paddingHorizontal: 2,
    paddingVertical: 2,
    marginLeft: 10,
  },
  roundButton: {
    height: 6,
    width: 6,
    borderRadius: 6 / 2,
    alignSelf: "center",
    marginRight: 5,
  },
  buttonText: {
    fontSize: 10,
    color: _COLORS.Kodie_DarkOrange,
    fontFamily: FONTFAMILY.K_Bold,
    alignSelf: "center",
  },
  flatListContainer: { marginHorizontal: 30, flex: 1 },
  expandedContent: {
    marginHorizontal: 30,
    flex: 1,
    flexDirection: "row",
    alignSelf: "center",
  },
  noteStyle: {
    flex: 1,
    flexDirection: "row",
    alignSelf: "flex-end",
    marginBottom: 15,
  },
  bottomModal_container: {
    borderWidth: 0.5,
    borderColor: _COLORS.Kodie_LightGrayColor,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    elevation: 10,
  },
  propertyRentMainView: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 16,
    marginTop: 10,
  },
  payButtonMainView: { justifyContent: "flex-end" },
  payButtonView: {
    backgroundColor: _COLORS.Kodie_WhiteColor,
    borderWidth: 1,
    borderColor: _COLORS.Kodie_GrayColor,
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 5,
  },
  payButtonText: {
    fontSize: 14,
    fontFamily: FONTFAMILY.K_Regular,
    color: _COLORS.Kodie_WhiteColor,
    alignSelf: "center",
    textAlign: "center",
  },
  LeftTextView: {
    justifyContent: "flex-start",
    flex: 1,
    alignSelf: "center",
  },
  LeftText: {
    fontSize: 10,
    fontFamily: FONTFAMILY.K_Regular,
    color: _COLORS.Kodie_BlackColor,
  },
  LeftTextRentText: {
    fontSize: 10,
    fontFamily: FONTFAMILY.K_Regular,
    color: _COLORS.Kodie_BlackColor,
  },
  leftIconsView: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignSelf: "center",
  },
  ImagesStyle: { height: 25, width: 25 },
  bedroomStl: {
    fontSize: 12,
    fontFamily: FONTFAMILY.K_Bold,
    alignSelf: "center",
    marginLeft: -10,
  },
  weeklyRent: { flex: 0.5, alignItems: "flex-end" },
  share_sty: { marginRight: 17 },
  bidsButton: {
    borderWidth: 1,
    borderColor: _COLORS.Kodie_GreenColor,
    backgroundColor: _COLORS.Kodie_GreenColor,
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
  },
  bidsButtonText: {
    fontSize: 11,
    fontFamily: FONTFAMILY.K_Regular,
    color: _COLORS.Kodie_WhiteColor,
  },
  biddingText: {
    fontSize: 10,
    fontFamily: FONTFAMILY.K_Regular,
    color: _COLORS.Kodie_BlackColor,
    marginLeft: 3,
  },
  daysViewStl: {
    borderWidth: 1,
    borderRadius: 8,
    borderColor: _COLORS.Kodie_GrayColor,
    marginLeft: 3,
    paddingHorizontal: 2,
  },
  Imagestl: { height: 80, width: 80 },
  margin: { marginLeft: 10 },
  flat_View: { justifyContent: "space-between" },
  bidView: { marginLeft: "25%" },
  bidText: {
    fontSize: 12,
    fontFamily: FONTFAMILY.K_Regular,
    color: _COLORS.Kodie_MediumGrayColor,
  },
  RoundImage: { height: 30, width: 30, borderRadius: 40 / 2 },
  StarView: {
    flex: 1,
    borderRadius: 50,
    borderWidth: 1,
    marginLeft: 80,
    paddingHorizontal: 4,
    paddingVertical: 2,
    elevation: 1,
    borderColor: _COLORS.Kodie_LiteWhiteColor,
  },
  starText: {
    fontSize: 9,
    color: _COLORS.Kodie_BlackColor,
    fontFamily: FONTFAMILY.K_Bold,
    marginLeft: 3,
  },
});
