const SUBSCRIPTION_ACTION_TYPES = {
    // for Subscription 
    API_SUBSCRIPTION:'API_SUBSCRIPTION',
    API_SUBSCRIPTION_SUCCESS: 'API_SUBSCRIPTION_SUCCESS',
    API_SUBSCRIPTION_ERROR: 'API_SUBSCRIPTION_ERROR',

    

  };
  export default SUBSCRIPTION_ACTION_TYPES;