import {Platform, StyleSheet} from 'react-native';
import {_COLORS, FONTFAMILY} from '../Themes';
export const MarketplacePropertyListingStyle = StyleSheet.create({
  flatListContainer: {marginHorizontal: 30},
  flat_MainView: {flex: 1, flexDirection: 'row', alignItems: 'center'},
  flexContainer: {flex: 1, alignSelf: 'center'},
  apartmentText: {
    fontSize: 13,
    color: _COLORS.Kodie_BlackColor,
    fontFamily: FONTFAMILY.K_Medium,
  },
  commontext: {
    fontSize: 16,
    color: _COLORS.Kodie_BlackColor,
    fontFamily: FONTFAMILY.K_Bold,
  },
  commonDay: {
    fontSize: 12,
    color: _COLORS.Kodie_BlackColor,
    fontFamily: FONTFAMILY.K_Bold,
  },
  commonRentview: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  commonRent: {
    fontSize: 12,
    color: _COLORS.Kodie_BlackColor,
    fontFamily: FONTFAMILY.K_Bold,
  },
  locationText: {
    flex: 1,
    fontSize: 10,
    color: _COLORS.Kodie_MediumGrayColor,
    // marginTop: 8,
    fontFamily: FONTFAMILY.K_Bold,
  },
  imageStyle: {
    // flex: 0.5,
    // height: 65,
    // width: 65,
    // borderRadius: 10,
    // alignSelf: 'center',
    // borderWidth: 1,
    // borderColor: _COLORS?.Kodie_GrayColor,
    height: 90,
    width: 90,
    borderRadius: 10,
    alignSelf: 'center',
    // borderWidth: 1,
    borderColor: _COLORS?.Kodie_GrayColor,
    marginHorizontal:10
  },
  Img_found: {
    fontSize: 12,
    color: _COLORS?.Kodie_BlackColor,
    textAlign: 'center',
    alignSelf: 'center',
  },
  noteStyle: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
    marginBottom: 15,
  },
  noteIcon: {height: 25, width: 25, marginRight: 8},
  buttonView: {
    flex: 0.4,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: _COLORS.Kodie_LightGrayColor,
    backgroundColor: _COLORS.Kodie_LightOrange,
    borderRadius: 20,
    // paddingVertical: 5,
    // marginLeft: '30%',
    // paddingBottom: 3,
  },
  buttonText: {
    fontSize: 12,
    color: _COLORS.Kodie_DarkOrange,
    fontFamily: FONTFAMILY.K_Bold,
    marginBottom: Platform.OS == 'android' ? 5 : 0,
    flex: 1,
    alignSelf: 'center',
    textAlign: 'center',
  },
  roundButton: {
    height: 6,
    width: 6,
    borderRadius: 6 / 2,
    alignSelf: 'center',
    // marginRight: 5,
  },
  expandedContent: {
    marginHorizontal: 30,
    flex: 1,
    flexDirection: 'row',
    alignSelf: 'center',
  },
  commonMidtext: {
    fontSize: 14,
    color: _COLORS.Kodie_MediumGrayColor,
    fontFamily: FONTFAMILY.K_Regular,
  },
  bottomModal_container: {
    borderWidth: 0.5,
    borderColor: _COLORS.Kodie_LightGrayColor,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    elevation: 10,
  },
  flat_MainView: {flexDirection: 'row', marginTop: 5},
  Container: {
    marginHorizontal: 16,
  },
  flatlistView: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: _COLORS.Kodie_GrayColor,
    paddingHorizontal: 10,
    paddingVertical: 2,
    marginTop: 15,
    marginHorizontal: 5,
    borderRadius: 15,
  },
  round: {
    height: 8,
    width: 8,
    borderRadius: 8 / 2,
    borderWidth: 1,
    borderColor: _COLORS.Kodie_LightGrayColor,
    backgroundColor: _COLORS.Kodie_GrayColor,
    alignSelf: 'center',
    marginRight: 5,
  },
  item_style: {
    fontSize: 12,
    fontFamily: FONTFAMILY.K_Regular,
    marginBottom: 4,
    alignSelf: 'center',
    textAlign: 'center',
    color: _COLORS.Kodie_VeryLightGrayColor,
  },
  crossIcon: {
    alignSelf: 'flex-end',
    marginHorizontal: 10,
  },
  bottomModal_container: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 10,
    paddingVertical: 15,
  },
});
