export const logos = {
  mainLogo: require("./../../assets/images/Logo/MainLogo.png"),
  KodieSplash: require("./../../assets/images/Logo/KodieSplash.png"),
  MainLogoWhite: require("./../../assets/images/Logo/MainLogoWhite.png"),
};

export const IMAGES = {
  GoogleIcon: require("../../assets/icons/google.png"),
  FacebookIcon: require("../../assets/icons/_Facebook.png"),
  userIcons: require("../../assets/icons/UploadPhotos.png"),
  Landlordprofile: require("../../assets/icons/landlordProfile.png"),
  uploadIcon: require("../../assets/icons/cloud-upload.png"),
  Upload: require("../../assets/icons/Upload.png"),
  document: require("../../assets/icons/doc-pdf.png"),
  cleaner: require("../../assets/icons/cleaner.png"),
  lightCleaner: require("../../assets/icons/lightCleaner.png"),
  outdoor: require("../../assets/icons/outdoor.png"),
  lightOutdorCleaner: require("../../assets/icons/lightOutdorCleaner.png"),
  heavyLifting: require("../../assets/icons/heavyLifting.png"),
  lightHeavylifting: require("../../assets/icons/lightHeavylifting.png"),
  fixingTool: require("../../assets/icons/fixingTool.png"),
  fixing: require("../../assets/icons/fixing.png"),
  filter: require("../../assets/icons/filter.png"),
  up_down_Arrow: require("../../assets/icons/up_down_Arrow.png"),
  userImage: require("../../assets/icons/UserImage.png"),
  redLine: require("../../assets/icons/RedLine.png"),
  blueLine: require("../../assets/icons/BlueLine.png"),
  greenLine: require("../../assets/icons/GreenLine.png"),
  noteBook: require("../../assets/icons/noteBook.png"),
  dashboard: require("../../assets/icons/dashboard-chart.png"),
  greenDeshboard: require("../../assets/icons/greenDeshboard.png"),
  property: require("../../assets/icons/property.png"),
  greenproperty: require("../../assets/icons/greenproperty.png"),
  repair: require("../../assets/icons/repair.png"),
  greenRepair: require("../../assets/icons/greenRepair.png"),
  chat: require("../../assets/icons/chat.png"),
  greenChat: require("../../assets/icons/greenChat.png"),
  View_property: require("../../assets/icons/View_property.png"),
  Documents: require("../../assets/icons/Documents.png"),
  Reminder: require("../../assets/icons/Reminder.png"),
  Chat_Tenant: require("../../assets/icons/Chat_Tenant.png"),
  Delete: require("../../assets/icons/Delete.png"),
  estimate: require("../../assets/icons/estimate.png"),
  contactDetails: require("../../assets/icons/contactDetails.png"),
  Account: require("../../assets/icons/Account.png"),
  Privacy: require("../../assets/icons/Privacy.png"),
  Notification: require("../../assets/icons/Notification.png"),
  FeedBack: require("../../assets/icons/FeedBack.png"),
  Contact: require("../../assets/icons/Contact.png"),
  SwitchAcc_: require("../../assets/icons/SwitchAcc_.png"),
  //Logout: require("../../assets/icons/Logout.png"),
  Subscription: require("../../assets/icons/Subscription.png"),
  Storage: require("../../assets/icons/Storage.png"),
  language: require("../../assets/icons/language.png"),
  helpCenter: require("../../assets/icons/helpCenter.png"),
  TermPrivacy: require("../../assets/icons/TermPrivacy.png"),
  contactus: require("../../assets/icons/contactus.png"),
  AppInfo: require("../../assets/icons/AppInfo.png"),
  Shape: require("../../assets/icons/Shape.png"),
  camera: require("../../assets/icons/camera.png"),
  gallery: require("../../assets/icons/gallery.png"),
  CheckIcon: require("../../assets/icons/checkIcon.png"),
  AspactRatio: require("../../assets/icons/aspactRatio.png"),
  Bathroom: require("../../assets/icons/bathroom.png"),
  BedroomIcon: require("../../assets/icons/bedroomIcon.png"),
  Parking: require("../../assets/icons/parking.png"),
  AddManually: require("../../assets/icons/AddManually.png"),
  // InviteTenant: require("../../assets/icons/InviteTenant.png"),
  // InviteContact: require("../../assets/icons/InviteContact.png"),
  Adduser: require("../../assets/icons/Adduser.png"),
  // diningRoom: require("../../assets/icons/diningRoom.png"),
  // Exterior: require("../../assets/icons/Exterior.png"),
  // Garage: require("../../assets/icons/Garage.png"),
  Garden: require("../../assets/icons/Garden.png"),
  kitchen: require("../../assets/icons/kitchen.png"),
  LivingRoom: require("../../assets/icons/LivingRoom.png"),
  Roof: require("../../assets/icons/Roof.png"),
  chrome: require("../../assets/icons/chrome.png"),
  firefox: require("../../assets/icons/firefox.png"),
  windows: require("../../assets/icons/windows.png"),
  locketone: require("../../assets/icons/locketone.png"),
  Duplicate: require("../../assets/icons/Duplicate.png"),
  lock: require("../../assets/icons/lock.png"),
  // common images
  Share: require("../../assets/images/Common/Share.png"),

  rightarrow: require("../../assets/icons/Rightarrow.png"),
  HelpCentre: require("../../assets/icons/HelpCentre.png"),
  ContactUs: require("../../assets/images/Common/ContactUs.png"),
  TermsandPolicy: require("../../assets/images/Common/TermsandPolicy.png"),
  AppInfoNew: require("../../assets/images/Common/TermsandPolicy.png"),
  instagram: require("../../assets/images/Common/instagram.png"),
  Facebook: require("../../assets/images/Common/Facebook.png"),
  linkdin: require("../../assets/images/Common/linkdin.png"),
  Twitter: require("../../assets/images/Common/Twitter.png"),

  Accountsetting: require("../../assets/images/Common/Accountsetting.png"),
  Autopayment: require("../../assets/images/Common/Autopayment.png"),
  kodiepayment: require("../../assets/images/Common/kodiepayment.png"),
  delete: require("../../assets/images/Common/delete.png"),
  changecontact: require("../../assets/images/Common/changecontact.png"),
  Logout: require("../../assets/images/Common/Logout.png"),
  RateKodie: require("../../assets/images/Common/RateKodie.png"),
  ManageSubscription: require("../../assets/images/Common/ManageSubscription.png"),
  Subscription: require("../../assets/images/Common/Subscription.png"),

  Done: require("../../assets/images/Common/Done.png"),
  NotificationIcon: require("../../assets/images/Common/NotificationIcon.png"),

  //Rahul
  kodie_icon: require("../../assets/icons/kodie_icon.png"),
  // menuIcon: require("../../assets/icons/menuIcon.png"),
  star: require("../../assets/icons/star.png"),
  RightLeftarrow: require("../../assets/icons/RightLeftArrow.png"),
  pencile: require("../../assets/icons/Vector.png"),
  HorizentalLine: require("../../assets/icons/HorizontallineImage.png"),
  upArrow: require("../../assets/icons/upaarow.png"),
  currency: require("../../assets/icons/Doller.png"),
  Inspections: require("../../assets/icons/Inspections.png"),
  Maintenancejobs: require("../../assets/icons/Maintenancejobs.png"),
  Noticesreminders: require("../../assets/icons/Notices&reminders.png"),
  Partner: require("../../assets/icons/Partner.png"),
  PropertyListing: require("../../assets/icons/PropertyListing.png"),
  RentalOffers: require("../../assets/icons/RentalOffers.png"),
  Reports: require("../../assets/icons/Reports.png"),
  Tenants: require("../../assets/icons/Tenants.png"),
  vacantProperties: require("../../assets/icons/vacantProperties.png"),
  ContractorDrawer: require("../../assets/icons/ContractorDrawer.png"),
  notificationbell: require("../../assets/icons/notificationbell.png"),
  Location: require("../../assets/icons/location.png"),
  pencile: require("../../assets/icons/Vector.png"),
  HorizentalLine: require("../../assets/icons/HorizontallineImage.png"),
  downarrow: require("../../assets/icons/downarrow.png"),
  verticalLine: require("../../assets/icons/verticalLineimg.png"),
  upArrow: require("../../assets/icons/upaarow.png"),
  Tax: require("../../assets/icons/Tax.png"),
  Group: require("../../assets/icons/Group.png"),
  Calendar: require("../../assets/icons/Calendar.png"),
  currency: require("../../assets/icons/Doller.png"),
  edit: require("../../assets/icons/edit.png"),
  Message: require("../../assets/icons/Message.png"),
  Mute: require("../../assets/icons/Mute.png"),
  Archive: require("../../assets/icons/Archive.png"),
  wifi: require("../../assets/icons/wifi.png"),
  visa: require("../../assets/icons/Visa.png"),
  Mastercard: require("../../assets/icons/Mastercard.png"),
  Base: require("../../assets/icons/BASE.png"),
  PayPal: require("../../assets/icons/PayPal.png"),
  GCash: require("../../assets/icons/GCash.png"),
};

export const BANNERS = {
  BannerFirst: require("../../assets/images/Banners/amico.png"),
  Apartment: require("../../assets/images/Banners/Apartment.png"),
  BannerSecond: require("../../assets/images/Banners/alfonso.png"),
  wallImage: require("../../assets/images/Banners/wall.png"),
  previewImage: require("../../assets/images/Banners/preview.png"),
  apartment: require("../../assets/images/Banners/Apartment.png"),
  house: require("../../assets/images/Banners/House.png"),
  cottage: require("../../assets/images/Banners/Cottage.png"),
};
