export const logos = {
  mainLogo: require("./../../assets/images/Logo/MainLogo.png"),
};

export const IMAGES = {
  GoogleIcon: require("../../assets/icons/google.png"),
  FacebookIcon: require("../../assets/icons/_Facebook.png"),
  userIcons: require("../../assets/icons/UploadPhotos.png"),
  Landlordprofile: require("../../assets/icons/landlordProfile.png"),
  uploadIcon: require("../../assets/icons/cloud-upload.png"),
  document: require("../../assets/icons/doc-pdf.png"),
  cleaner: require("../../assets/icons/cleaner.png"),
  lightCleaner: require("../../assets/icons/lightCleaner.png"),
  outdoor: require("../../assets/icons/outdoor.png"),
  lightOutdorCleaner: require("../../assets/icons/lightOutdorCleaner.png"),
  heavyLifting: require("../../assets/icons/heavyLifting.png"),
  lightHeavylifting: require("../../assets/icons/lightHeavylifting.png"),
  fixingTool: require("../../assets/icons/fixingTool.png"),
  fixing: require("../../assets/icons/fixing.png"),
  filter: require("../../assets/icons/filter.png"),
  userImage: require("../../assets/icons/UserImage.png"),
  redLine: require("../../assets/icons/RedLine.png"),
  blueLine: require("../../assets/icons/BlueLine.png"),
  greenLine: require("../../assets/icons/GreenLine.png"),
  noteBook: require("../../assets/icons/noteBook.png"),
  dashboard: require("../../assets/icons/dashboard-chart.png"),
  greenDeshboard: require("../../assets/icons/greenDeshboard.png"),
  property: require("../../assets/icons/property.png"),
  greenproperty: require("../../assets/icons/greenproperty.png"),
  repair: require("../../assets/icons/repair.png"),
  greenRepair: require("../../assets/icons/greenRepair.png"),
  chat: require("../../assets/icons/chat.png"),
  greenChat: require("../../assets/icons/greenChat.png"),
  View_property: require("../../assets/icons/View_property.png"),
  Documents: require("../../assets/icons/Documents.png"),
  Reminder: require("../../assets/icons/Reminder.png"),
  Chat_Tenant: require("../../assets/icons/Chat_Tenant.png"),
  Delete: require("../../assets/icons/Delete.png"),
  estimate: require("../../assets/icons/estimate.png"),
  contactDetails: require("../../assets/icons/contactDetails.png"),
  Account: require("../../assets/icons/Account.png"),
  Privacy: require("../../assets/icons/Privacy.png"),
  Notification: require("../../assets/icons/Notification.png"),
  FeedBack: require("../../assets/icons/FeedBack.png"),
  Contact: require("../../assets/icons/Contact.png"),
  SwitchAcc_: require("../../assets/icons/SwitchAcc_.png"),
  Logout: require("../../assets/icons/Logout.png"),
  Subscription: require("../../assets/icons/Subscription.png"),
  Storage: require("../../assets/icons/Storage.png"),
  language: require("../../assets/icons/language.png"),
  helpCenter: require("../../assets/icons/helpCenter.png"),
  TermPrivacy: require("../../assets/icons/TermPrivacy.png"),
  contactus: require("../../assets/icons/contactus.png"),
  AppInfo: require("../../assets/icons/AppInfo.png"),
  Shape: require("../../assets/icons/Shape.png"),
  camera: require("../../assets/icons/camera.png"),
  gallery: require("../../assets/icons/gallery.png"),
  CheckIcon: require("../../assets/icons/checkIcon.png"),
  AspactRatio: require("../../assets/icons/aspactRatio.png"),
  Bathroom: require("../../assets/icons/bathroom.png"),
  BedroomIcon: require("../../assets/icons/bedroomIcon.png"),
  Parking: require("../../assets/icons/parking.png"),
    // common images
    Share: require("../../assets/images/Common/Share.png"),
  
};

export const BANNERS = {
  BannerFirst: require("../../assets/images/Banners/amico.png"),
  Apartment: require("../../assets/images/Banners/Apartment.png"),
  BannerSecond: require("../../assets/images/Banners/alfonso.png"),
  wallImage: require("../../assets/images/Banners/wall.png"),
  previewImage: require("../../assets/images/Banners/preview.png"),
  apartment: require("../../assets/images/Banners/Apartment.png"),
  house: require("../../assets/images/Banners/House.png"),
  cottage: require("../../assets/images/Banners/Cottage.png"),
};
